import { motion, useMotionValue, useSpring } from 'framer-motion';
import { Shield, MapPin, BookOpen, Mic2, ArrowDown, Quote } from 'lucide-react';
import PageLayout from '../components/PageLayout'; import Button from '../components/Button'; import SectionTitle from '../components/SectionTitle'; import ScrollReveal from '../components/ScrollReveal'; import BookCard from '../components/BookCard'; import FAQAccordion from '../components/FAQAccordion'; import { books } from '../data/books'; import { timeline } from '../data/timeline';
const genres=['Historical Crime','Warwick History','Victorian Britain','Detective Fiction','Ghost Stories','True Crime','British History'];
export default function Home(){const x=useSpring(useMotionValue(0),{stiffness:80,damping:18}),y=useSpring(useMotionValue(0),{stiffness:80,damping:18}); const move=e=>{const r=e.currentTarget.getBoundingClientRect();x.set((e.clientX-r.left-r.width/2)/20);y.set((e.clientY-r.top-r.height/2)/20)}; return <PageLayout>
  <section className="hero" onMouseMove={move}><div className="hero-bg"/><div className="hero-copy"><span className="eyebrow">Author · Historian · Storyteller</span><h1 className="upcoming-title">Early One Morning <em>and Other Stories</em></h1><p>A forthcoming collection of atmospheric stories from Graham Sutherland.</p><div className="button-row"><Button to="/books" className="coming-soon-button">Coming Soon</Button><Button to="/books" variant="outline">Explore the books</Button></div></div><motion.div className="hero-book" style={{x,y}}><span className="hero-book-status">Coming Soon</span><img src="/images/early-one-morning-book.png" alt="Early One Morning and Other Stories by Graham Sutherland"/></motion.div><a className="scroll-cue" href="#story"><ArrowDown/> Scroll to explore</a></section>
  <div className="marquee"><div>{[...genres,...genres].map((g,i)=><span key={i}>{g}<b>✦</b></span>)}</div></div>
  <section className="about-preview section cream" id="story"><ScrollReveal className="about-art"><div className="portrait-frame"><img className="author-photo" src="/images/graham-sutherland-portrait.jpg" alt="Graham Sutherland at a ceremonial engagement"/></div><div className="roundel">Author<br/>Historian<br/>Storyteller</div></ScrollReveal><ScrollReveal className="about-copy" delay={.1}><SectionTitle eyebrow="About the author" title={<>A lifetime immersed in<br/><em>history & investigation.</em></>} /><p>Graham Sutherland is a retired Warwickshire police inspector, historian, author and public speaker. His policing career and work with the Warwickshire Constabulary Historical Association gave him a rare understanding of Victorian policing and crime detection.</p><p>He has lived in Warwick for more than fifty years and writes about local history, crime and British social history.</p><div className="facts"><div><Shield/><small>Former career</small><b>Police Inspector</b></div><div><MapPin/><small>Based in</small><b>Warwick, England</b></div><div><BookOpen/><small>Specialism</small><b>Crime & History</b></div><div><Mic2/><small>Also known for</small><b>Public Speaking</b></div></div><Button to="/about" variant="dark">Read Graham's story</Button></ScrollReveal></section>
  <section className="featured section dark"><ScrollReveal className="featured-cover"><span className="cover-glow"/><span className="featured-status">Coming Soon</span><img src="/images/early-one-morning-book.png" alt="Early One Morning and Other Stories book"/></ScrollReveal><ScrollReveal className="featured-copy"><SectionTitle light eyebrow="Upcoming publication" title={<>Early One Morning <em>and Other Stories</em></>}/><p>A forthcoming collection of atmospheric stories from Graham Sutherland.</p><div className="tags"><span>Short Stories</span><span>Crime</span><span>Mystery</span></div><Button to="/books">Coming Soon</Button></ScrollReveal></section>
  <section className="section bookshelf"><SectionTitle eyebrow="Selected works" title="The Book Shelf" copy="Historical works and crime fiction shaped by Graham's lifelong fascination with Warwick, policing and Britain's past."/><div className="book-grid">{books.slice(0,4).map((b,i)=><ScrollReveal key={b.id} delay={i*.08}><BookCard book={b} index={i}/></ScrollReveal>)}</div><div className="center"><Button to="/books" variant="dark">View full book shelf</Button></div></section>
  <section className="legacy section dark"><div className="legacy-heading"><SectionTitle light eyebrow="A life in stories" title="Career & Literary Legacy"/><p>From public service to published history, explore the defining chapters behind a lifetime of investigation, research and storytelling.</p><div className="legacy-intro"><span>The thread running through the work</span><p>Every street holds a story.<br/><em>Every archive offers a clue.</em></p></div><div className="legacy-summary"><span><b>60+</b> years of stories</span><span><b>08</b> defining chapters</span></div></div><div className="timeline">{timeline.map((t,i)=><ScrollReveal className="timeline-item" key={t[0]} delay={i*.04}><span className="timeline-index">{String(i+1).padStart(2,'0')}</span><div className="timeline-marker"><i/></div><div className="timeline-card"><span>{t[0]}</span><p>{t[1]}</p></div></ScrollReveal>)}</div></section>
  <section className="quote-banner"><div><Quote/><p>Warwick's streets hold centuries of <em>crime, conflict, mystery</em> and extraordinary human lives.</p></div></section>
  <section className="section book-testimonials"><div className="testimonials-heading"><SectionTitle eyebrow="The reader experience" title={<>Stories that stay<br/><em>with you.</em></>}/><div className="reader-rating"><strong>4.17</strong><div><span>★★★★★</span><small>Reader rating for Bloody British History: Warwick</small></div></div></div><div className="testimonial-grid"><ScrollReveal className="testimonial-card"><Quote/><p>Atmospheric crime fiction grounded in the streets, secrets and social history of Warwick.</p><div><b>Mayfield’s Law</b><span>Historical crime fiction</span></div></ScrollReveal><ScrollReveal className="testimonial-card featured-testimonial" delay={.08}><Quote/><p>Local history told with an investigator’s eye—full of dark events, extraordinary characters and unexpected detail.</p><div><b>Bloody British History: Warwick</b><span>British history</span></div></ScrollReveal><ScrollReveal className="testimonial-card" delay={.16}><Quote/><p>Carefully researched stories that make the past feel immediate, human and impossible to forget.</p><div><b>Graham’s historical works</b><span>History · Crime · Warwick</span></div></ScrollReveal></div><p className="testimonial-note">Editorial reader-experience summaries based on the books’ published descriptions. Rating shown from Goodreads.</p></section>
  <section className="section faq-section dark"><SectionTitle light eyebrow="Questions & answers" title="From the reading room"/><FAQAccordion/></section>
  <section className="cta section"><span className="eyebrow">Discover Warwick anew</span><h2>Step inside Warwick's<br/><em>extraordinary past.</em></h2><p>Explore Graham's publications, discover the stories behind his writing, or get in touch regarding author and speaking enquiries.</p><div className="button-row"><Button to="/books">Explore books</Button><Button to="/contact" variant="outline">Contact Graham</Button></div></section>
 </PageLayout>}
